site_name: Census Data Model Documentation
site_url: https://takinsolutions.github.io/censusdocumentation/
use_directory_urls: true
# pagination
nav:
    - Data Model: index.md
    - Antique Monument: antique_monument.md
    - Postclassical Work: posclassical_work.md
    - Person: person.md
    - Group: group.md
    - Bibliographic Entity: bibliography.md
    - Location: location.md
    - Period: period.md
    - Image: image.md
    - Collections: collections.md
theme: windmill
markdown_extensions:
  - attr_list
  - md_in_html
  - tables

